<?xml version="1.0" ?>
<robot name="name" xmlns:xacro="http://www.ros.org/wiki/xacro">
	
<xacro:include filename="macros.xacro"/>
<xacro:include filename="params.xacro"/>
	
<link name="base_link">
	<xacro:inertia m="10"/>
</link>

<joint name="joint_1" type="revolute">
	<parent link="base_link"/>
	<child link="link_1"/>
	<origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
	<axis xyz="1 0 0"/>
	<limit lower="${-pi/2}" upper="${pi/2}" velocity="100" effort="500"/>
</joint>

<link name="link_1">
	<xacro:inertia m="2.5"/>
	<origin xyz="0 0 ${-link_length/2}" rpy="0 0 0"/>
</link>

<joint name="joint_2" type="revolute">
	<parent link="link_1"/>
	<child link="link_2"/>
	<origin xyz="0 0 ${link_length/2}" rpy="0 0 0"/>
	<axis xyz="1 0 0"/>
	<limit lower="${-pi/2}" upper="${pi/2}" velocity="100" effort="500"/>
</joint>

<link name="link_2">
	<xacro:inertia m="2.5"/>
	<origin xyz="0 0 ${-link_length/2}" rpy="0 0 0"/>
</link>
	
</robot>
