<?xml version="1.0" ?>
<robot name="robot" xmlns:xacro="http://www.ros.org/wiki/xacro">
	
<xacro:property name="arm_01_len" value="0.2" />
<xacro:property name="arm_01_mass" value="0.025" />
<xacro:property name="arm_02_len" value="0.2" />
<xacro:property name="arm_02_mass" value="0.025" />
<xacro:property name="arm_03_len" value="0.2" />
<xacro:property name="arm_03_mass" value="0.025" />
<xacro:property name="arm_04_len" value="0.25" />
<xacro:property name="arm_04_mass" value="0.025" />
<xacro:property name="offset" value="0" />

<!-- base link of the manipulator -->
<link name="arm_base_link">
	<origin 
		xyz="0 0 0"
		rpy="0 0 0" />
	
	<inertial>
		<mass value="0.1"/>
  		<origin xyz="0 0 0" rpy="0 0 0" />
  		<inertia 
			ixx="0.0000416666667" iyy="0.0000416666667" izz="0.0000416666667" 
			iyz="0" ixy="0" ixz="0" />
	</inertial>
  	
  	<collision>
		<origin xyz="0 0 0" rpy="0 0 0"/>
		<geometry>
			<box size="0.1 0.1 0.1"/>
		</geometry>
  	</collision>
  	
  	<visual>
		<origin xyz="0 0 0" rpy="0 0 0"/>
		<geometry>
			<box size="0.1 0.1 0.1"/>
		</geometry>
		<material name="red" />
  	</visual>
</link>
<!-- base link of the manipulator -->



<!-- first link of the manipulator -->
<joint name="arm_joint_01" type="revolute">
	<parent link="arm_base_link"/>
	<child link="arm_link_01"/>
	<origin rpy="0 0 0" xyz="0 0 ${0.05 + offset}"/>
	
	<axis xyz="0 0 1"/>
	<limit effort="1000.0" lower="-3.12" upper="3.139" velocity="5"/>
</joint>

<link name="arm_link_01">
	<origin 
		xyz="0 0 0"
		rpy="0 0 0" />
	
	<inertial>
		<origin xyz="0 0 ${arm_01_len/2}" rpy="0 0 0" />
		<mass value="${arm_01_mass}"/>
		<xacro:cylinder_inertia mass="${arm_01_mass}" r="0.04" l="${arm_01_len}" />
	</inertial>
	
	<collision>
		<origin xyz="0 0 ${arm_01_len/2}" rpy="0 0 0"/>
		<geometry>
			<cylinder radius="0.04" length="${arm_01_len}"/>
		</geometry>
	</collision>
	
	<visual>
		<origin xyz="0 0 ${arm_01_len/2}" rpy="0 0 0"/>
		<geometry>
			<cylinder radius="0.04" length="${arm_01_len}"/>
		</geometry>
		<material name="red" />
	</visual>
</link>
<!-- first link of the manipulator -->



<!-- second link of the manipulator -->
<joint name="arm_joint_02" type="revolute">
	<parent link="arm_link_01"/>
	<child link="arm_link_02"/>
	<origin rpy="0 0 0" xyz="0 0 ${arm_01_len + offset}"/>
	<axis xyz="0 1 0"/>
	<limit effort="1000.0" lower="-1.8" upper="1.8" velocity="5"/>
</joint>

<link name="arm_link_02">
	<origin 
		xyz="0 0 0"
		rpy="0 0 0" />
	
	<inertial>
		<origin xyz="0 0 ${arm_02_len/2}" rpy="0 0 0" />
		<mass value="${arm_02_mass}"/>
		<xacro:cylinder_inertia mass="${arm_02_mass}" r="0.04" l="${arm_02_len}" />
	</inertial>
  	
	<collision>
		<origin xyz="0 0 ${arm_02_len/2}" rpy="0 0 0"/>
		<geometry>
			<cylinder radius="0.04" length="${arm_02_len}"/>
		</geometry>
	</collision>
  	
	<visual>
		<origin xyz="0 0 ${arm_02_len/2}" rpy="0 0 0"/>
		<geometry>
			<cylinder radius="0.04" length="${arm_02_len}"/>
		</geometry>
		<material name="red" />
	</visual>
</link>
<!-- second link of the manipulator -->



<!-- third link of the manipulator -->
<joint name="arm_joint_03" type="revolute">
	<parent link="arm_link_02"/>
	<child link="arm_link_03"/>
	<origin rpy="0 0 0" xyz="0 0 ${arm_02_len + offset}"/>
	<axis xyz="0 1 0"/>
	<limit effort="1000.0" lower="-1.8" upper="1.8" velocity="5"/>
</joint>

<link name="arm_link_03">
	<origin 
		xyz="0 0 0"
		rpy="0 0 0" />
	
	<inertial>
		<origin xyz="0 0 ${arm_03_len/2}" rpy="0 0 0" />
		<mass value="${arm_03_mass}"/>
		<xacro:cylinder_inertia mass="${arm_03_mass}" r="0.04" l="${arm_03_len}" />
	</inertial>
  	
	<collision>
		<origin xyz="0 0 ${arm_03_len/2}" rpy="0 0 0"/>
		<geometry>
			<cylinder radius="0.04" length="${arm_03_len}"/>
		</geometry>
	</collision>
  	
	<visual>
		<origin xyz="0 0 ${arm_03_len/2}" rpy="0 0 0"/>
		<geometry>
			<cylinder radius="0.04" length="${arm_03_len}"/>
		</geometry>
		<material name="red" />
	</visual>
</link>
<!-- third link of the manipulator -->



<!-- last link of the manipulator, base gripper -->
<joint name="arm_joint_04" type="revolute">
	<parent link="arm_link_03"/>
	<child link="arm_link_04"/>
	<origin rpy="0 0 0" xyz="0 0 ${arm_03_len + offset}"/>
	<axis xyz="0 1 0"/>
	<limit effort="10000.0" lower="-1.8" upper="1.8" velocity="5"/>
</joint>

<link name="arm_link_04">
	<origin 
		xyz="0 0 0"
		rpy="0 0 0" />
	
	<inertial>
		<origin xyz="0 0 0.04" rpy="0 0 0" />
		<mass value="${arm_04_mass}"/>
		<inertia
			ixx="0.000010279" iyy="0.000010279" izz="0.000007225" 
			ixy="0" ixz="0" iyz="0"/>
	</inertial>
  	
	<collision>
		<origin xyz="0 0 0.04" rpy="0 0 0"/>
		<geometry>
			<box size="0.034 0.2 0.08"/>
		</geometry>
	</collision>
  	
	<visual>
		<origin xyz="0 0 0.04" rpy="0 0 0"/>
		<geometry>
			<box size="0.034 0.2 0.08"/>
		</geometry>
		<material name="red" />
	</visual>
</link>
-->
<!-- last link of the manipulator, base gripper -->



<!-- right gripper -->
<joint name="right_grip_joint" type="prismatic">
	<parent link="arm_link_04"/>
	<child link="right_grip_link"/>
	<origin rpy="0 0 0" xyz="${0.015 + 0.03} 0.05 0.04"/>
	<axis xyz="0 1 0"/>
	<limit effort="1000.0" lower="-0.04" upper="0.035" velocity="6.5"/>
</joint>
  
<link name="right_grip_link">
	<origin 
		xyz="0 0 0"
		rpy="0 0 0" />
	
	<inertial>
		<mass value="0.01"/>
		<origin xyz="0 0 0" rpy="0 0 0" />
		<inertia ixx="0.000010279" ixy="0" ixz="0" iyy="0.000010279" iyz="0" izz="0.000007225"/>
	</inertial>
	
	<collision>
		<origin rpy="0 0 0" xyz="0 0 0"/>
		<geometry>
			<box size="0.06 0.02 0.08"/>
		</geometry>
	</collision>
  	
  	<visual>
		<origin rpy="0 0 0" xyz="0 0 0"/>
		<geometry>
			<box size="0.06 0.02 0.08"/>
		</geometry>
		<material name="white" />
  	</visual>
</link>
<!-- right gripper -->



<!-- left gripper -->
<joint name="left_grip_joint" type="prismatic">
	<parent link="arm_link_04"/>
	<child link="left_grip_link"/>
	<origin rpy="0 0 0" xyz="${0.015 + 0.03} -0.05 0.04"/>
	<axis xyz="0 1 0"/>
	<limit effort="1000.0" upper="0.04" lower="-0.035" velocity="6.5"/>
</joint>

<link name="left_grip_link">
	<origin 
		xyz="0 0 0"
		rpy="0 0 0" />
	
  	<inertial>
		<mass value="0.01"/>
		<origin xyz="0 0 0" rpy="0 0 0" />
		<inertia ixx="0.000010279" ixy="0" ixz="0" iyy="0.000010279" iyz="0" izz="0.000007225"/>
  	</inertial>
  	
  	<collision>
		<origin rpy="0 0 0" xyz="0 0 0"/>
		<geometry>
			<box size="0.06 0.02 0.08"/>
		</geometry>
  	</collision>
  	
  	<visual>
		<origin rpy="0 0 0" xyz="0 0 0"/>
		<geometry>
			<box size="0.06 0.02 0.08"/>
		</geometry>
		<material name="white" />
  	</visual>
</link>
<!-- left gripper -->

</robot>
