<?xml version="1.0" ?>
<robot name="robot" xmlns:xacro="http://www.ros.org/wiki/xacro">
	
<xacro:property name="arm_01_len" value="0.25" />
<xacro:property name="arm_02_len" value="0.5" />
<xacro:property name="arm_03_len" value="0.125" />

<!-- base link of the manipulator -->
<link name="arm_base_link">
	<origin 
		xyz="0 0 0"
		rpy="0 0 0" />
	
	
	<inertial>
		<mass value="0.1"/>
  		<origin xyz="0 0 0" rpy="0 0 0" />
  		<inertia 
			ixx="0.0000416666667" iyy="0.0000416666667" izz="0.0000416666667" 
			iyz="0" ixy="0" ixz="0" />
	</inertial>
  	
  	<collision>
		<origin xyz="0 0 0" rpy="0 0 0"/>
		<geometry>
			<box size="0.1 0.1 0.1"/>
		</geometry>
  	</collision>
  	
  	<visual>
		<origin xyz="0 0 0" rpy="0 0 0"/>
		<geometry>
			<box size="0.1 0.1 0.1"/>
		</geometry>
		<material name="red" />
  	</visual>
</link>
<!-- base link of the manipulator -->



<!-- first link of the manipulator -->
<joint name="arm_joint_01" type="revolute">
	<parent link="arm_base_link"/>
	<child link="arm_link_01"/>
	<origin rpy="0 0 0" xyz="0 0 ${arm_01_len/2}"/>
	
	<axis xyz="0 0 1"/>
	<limit effort="1000.0" lower="-3.14" upper="3.14" velocity="0.2"/>
</joint>

<link name="arm_link_01">
	<origin 
		xyz="0 0 0"
		rpy="0 0 0" />
	
	<inertial>
		<mass value="0.025"/>
		<origin xyz="0 0 0" rpy="0 0 0" />
		<inertia ixx="0.000010279" ixy="0" ixz="0" iyy="0.000010279" iyz="0" izz="0.000007225"/>
	</inertial>
	
	<collision>
		<origin xyz="0 0 0" rpy="0 0 0"/>
		<geometry>
			<cylinder radius="0.04" length="${arm_01_len}"/>
		</geometry>
	</collision>
	
	<visual>
		<origin xyz="0 0 0" rpy="0 0 0"/>
		<geometry>
			<cylinder radius="0.04" length="${arm_01_len}"/>
		</geometry>
		<material name="red" />
	</visual>
</link>
<!-- first link of the manipulator -->



<!-- second link of the manipulator -->
<joint name="arm_joint_02" type="revolute">
	<parent link="arm_link_01"/>
	<child link="arm_link_02"/>
	<origin rpy="0 0 0" xyz="0 0 ${arm_02_len/2}"/>
	<axis xyz="1 0 0"/>
	<limit effort="1000.0" lower="-1.8" upper="1.8" velocity="0.2"/>
</joint>

<link name="arm_link_02">
	<origin 
		xyz="0 0 0"
		rpy="0 0 0" />
	
	<inertial>
		<mass value="0.025"/>
		<origin xyz="0 0 0" rpy="0 0 0" />
		<inertia
			ixx="0.000010279" iyy="0.000010279" izz="0.000007225" 
			ixy="0" ixz="0" iyz="0"/>
	</inertial>
  	
	<collision>
		<origin xyz="0 0 ${arm_02_len/2}" rpy="0 0 0"/>
		<geometry>
			<cylinder radius="0.04" length="${arm_02_len}"/>
		</geometry>
	</collision>
  	
	<visual>
		<origin xyz="0 0 ${arm_02_len/2}" rpy="0 0 0"/>
		<geometry>
			<cylinder radius="0.04" length="${arm_02_len}"/>
		</geometry>
		<material name="red" />
	</visual>
</link>
<!-- second link of the manipulator -->



<!-- third link of the manipulator -->
<!--
<joint name="arm_joint_03" type="revolute">
	<parent link="arm_link_02"/>
	<child link="arm_link_03"/>
	<origin rpy="0 0 0" xyz="0 0 ${arm_03_len/2}"/>
	<axis xyz="1 0 0"/>
	<limit effort="1000.0" lower="-1.8" upper="1.8" velocity="0.2"/>
</joint>

<link name="arm_link_03">
	<origin 
		xyz="0 0 0"
		rpy="0 0 0" />
	
	<inertial>
		<mass value="0.025"/>
		<origin xyz="0 0 0" rpy="0 0 0" />
		<inertia
			ixx="0.000010279" iyy="0.000010279" izz="0.000007225" 
			ixy="0" ixz="0" iyz="0"/>
	</inertial>
  	
	<collision>
		<origin xyz="0 0 0" rpy="0 0 0"/>
		<geometry>
			<cylinder radius="0.04" length="${arm_03_len}"/>
		</geometry>
	</collision>
  	
	<visual>
		<origin xyz="0 0 0" rpy="0 0 0"/>
		<geometry>
			<cylinder radius="0.04" length="${arm_03_len}"/>
		</geometry>
		<material name="red" />
	</visual>
</link>
-->
<!-- third link of the manipulator -->



<!-- last link of the manipulator -->
<!--
<joint name="arm_joint_04" type="revolute">
	<parent link="arm_link_02"/>
	<child link="arm_link_03"/>
	<origin rpy="0 0 0" xyz="0 0 ${arm_04_len/2}"/>
	<axis xyz="1 0 0"/>
	<limit effort="1000.0" lower="-1.8" upper="1.8" velocity="0.2"/>
</joint>

<link name="arm_link_04">
	<origin 
		xyz="0 0 0"
		rpy="0 0 0" />
	
	<inertial>
		<mass value="0.025"/>
		<origin xyz="0 0 0" rpy="0 0 0" />
		<inertia
			ixx="0.000010279" iyy="0.000010279" izz="0.000007225" 
			ixy="0" ixz="0" iyz="0"/>
	</inertial>
  	
	<collision>
		<origin xyz="0 0 0" rpy="0 0 0"/>
		<geometry>
			<cylinder radius="0.04" length="${arm_04_len}"/>
		</geometry>
	</collision>
  	
	<visual>
		<origin xyz="0 0 0" rpy="0 0 0"/>
		<geometry>
			<cylinder radius="0.04" length="${arm_04_len}"/>
		</geometry>
		<material name="red" />
	</visual>
</link>
-->
<!-- last link of the manipulator -->
</robot>
