# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: my_arm
  joint_model_group_pose: up
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - arm_base_to_base
    - arm_joint_01
    - arm_joint_02
    - arm_joint_03
    - arm_joint_04
    - left_grip_joint
    - right_grip_joint
    - joint_left_wheel
    - joint_right_wheel
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: my_arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - arm_base_to_base
      - arm_joint_01
      - arm_joint_02
      - arm_joint_03
      - arm_joint_04
my_arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - arm_base_to_base
    - arm_joint_01
    - arm_joint_02
    - arm_joint_03
    - arm_joint_04
  gains:
    arm_base_to_base:
      p: 10
      d: 0
      i: 0
      i_clamp: 0
    arm_joint_01:
      p: 10
      d: 0
      i: 0
      i_clamp: 0
    arm_joint_02:
      p: 10
      d: 1
      i: 1
      i_clamp: 0
    arm_joint_03:
      p: 10
      d: 0
      i: 0
      i_clamp: 0
    arm_joint_04:
      p: 10
      d: 0
      i: 0
      i_clamp: 0
